version: '3.8'
services:
  mqtt-broker:
    image: eclipse-mosquitto:latest
    container_name: mqtt-broker
    restart: always
    ports:
      - '1883:1883' # MQTT 기본 포트
      - '9001:9001' # WebSocket 포트
    volumes:
      - ./docker/mosquitto/config:/mosquitto/config # 설정 파일
      - ./docker/mosquitto/data:/mosquitto/data # 데이터
      - ./docker/mosquitto/log:/mosquitto/log # 로그
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379' # Redis 기본 포트
    volumes:
      - ./docker/redis/config:/usr/local/etc/redis
      - ./docker/redis/data:/data
      - ./docker/redis/log:/var/log/redis
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']
